book/bookproject/book/urls.py
from django.urls import path
from.import views
from .views import like_post, posts_view

app_name = 'posts'

urlpatterns=[
    path('book/',views.ListBookView.as_view(),name='list-book'),
    path('book/<int:pk>/detail/',views.DetailBookView.as_view()),
    path('book/toukou/',views.Toukou.as_view(), name='create'),
    path('book/<int:pk>/delete/', views.Delete.as_view(), name='delete'),
    path('book/<int:pk>/update/', views.Update.as_view(), name='update'),
    path('like/', like_post, name='like-post'),
    path('', posts_view, name='post-list'),
]

book/bookproject/bookproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('book.urls')),
    path('posts/', include('book.urls', namespace='posts'))
]

book/bookproject/book/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Book(models.Model):
    title = models.CharField(max_length = 100)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    liked = models.ManyToManyField(User, default=None, blank=True, related_name='liked')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author')

    def __str__(self):
        return str(self.title)

    @property
    def num_likes(self):
        return self.liked.all().count()

LIKE_CHOICES = (
    ('Like', 'Like'),
    ('Unlike', 'Unlike'),
)

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Book, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES, default='Like', max_length=10)

    def __str__(self):
        return str(self.post)

book/bookproject/bookproject/__pycache__/models.py
from django.db import models 
from datetime import timezone


class Book(models.Model):
    title = models.CharField(max_length = 100)
    text = models.TextField()
    # add_date=models.DateField(
    #     blank=True,
    #     null=True,
    #     dafault=timezone.now()
    # )
    
# Book.objects.order_by( '-id' )
# Reserved.objects.all().filter(client=client_id).order_by('check_in') 
# Data.objects.order_by('date').reverse().first()

# Create your models here.

book/bookproject/book/forms.py
from django import forms
from .models import book

class BookForm(forms.ModelsForm):
    class Meta:
        models=book
        fields=('title','text')

        widget={
            'title':forms.TextInput(attrs={'class':'bookTitle'}),#タイトル
            'text':forms.TextInput(attrs={'class':'bookText'}),#コメント
    
        }

book/bookproject/book/views.py
from django.shortcuts import render, redirect
from django.views.generic import (ListView,DetailView,CreateView,DeleteView,UpdateView,)
from.models import Book, Like
from django.urls import reverse,reverse_lazy


class ListBookView(ListView):
    object_list = Book.objects.order_by('id').reverse()
    template_name='book/Diary.html'
    model=Book 
    
    # object_list = Book.objects.order_by('id')
    # return render(request, 'book/Diary.html', {'object_list':object_list})


class DetailBookView(DetailView):
    template_name='book/book_detail.html'
    model=Book

class Toukou(CreateView):
    template_name = 'book/toukou.html'
    model = Book
    fields = ('title','text')
    success_url = reverse_lazy('list-book')

class Delete(DeleteView):
    template_name = 'book/book_confirm_delete.html'
    model = Book
    success_url = reverse_lazy('list-book')


class Update(UpdateView):
    template_name = 'book/book_update.html'
    model = Book
    fields = ('title', 'text')
    success_url = reverse_lazy('list-book')

    
# def index_view(request):
#     object_list = Book.objects.order_by('id')
#     return render(request, 'book/Diary.html', {'object_list':object_list})

def like_post(request):
    user = request.user
    if request.method == 'POST':
        book_id = request.POST.get('book_id')
        book_obj = Book.objects.get(id=book_id)

        if user in book_obj.liked.all():
            book_obj.liked.remove(user)
        else:
            book_obj.liked.add(user)

        like, created = Like.objects.get_or_create(user=user, book_id=book_id)

        if not created:
            if like.value == 'Like':
                like.value = 'Unlike'
            else:
                like.value = 'Like'

        like.save()
    return redirect('posts:post-list')

def posts_view(request):
    qs = Book.objects.all()
    user = request.user

    context = {
        'qs': qs,
        'user': user,
    }

    return render(request, 'book/Dairy.html', context)

book/bookproject/book/templates/book/Diary.html
{% extends 'book/base.html' %}

{% block title %}
{% endblock title %}
{% comment %} <html>

<head>
  <title>AI</title>
  <meta charset="UTF-8" />
  {% load static %}
  <link href="{% static 'css/Diary.css' %}" rel="stylesheet" />
</head>

<body> {% endcomment %}
  {% block content %}
  <div class="app">
    <div class="main">
      <div class="sidebar">
        <h1 id="logo">
          <img src="../images/aiabana-.jpg" width="250" height="150" alt="トップ">
        </h1>
        <ul>
          <li class="top-line"><a href="../index/index.html">ホーム</a></li>
          <li><a href="../Mypage/Mypage.html">マイページへ</a></li>
          <li><a href="../Good/Good.html">いいね</a></li>
          <li><a href="../Diary/Diary.html" class="current">日記</a></li>
          <li><a href="../Chat/Chat.html">チャット</a></li>
        </ul>
      </div>
      <div class="content">
        <div class="titlebar">
          <h2>日記</h2>
          <form action="ページ内検索のURL" method="get" class="Search">
            <input type="search" name="search" placeholder="キーワードを入力">
            <input type="submit" class="button-space" name="submit" value="検索">
          </form>
        </div>
        {% for obj in qs  %}
        <div class="card">
          <div class="text1">
            <h5>{{obj.title}}</h5><!--タイトル-->
            <p>{{obj.text}}</p><!--コメント-->
            <h6>投稿者: {{obj.author}}</h6><!--ユーザー名-->
            <form action="{% url 'posts:like-post' %}" method='POST' class="ui form">
              {% csrf_token %}
              <input type='hidden' name='post_id' value="{{ obj.id }}">
              {% if user not in obj.liked.all %}
                  <button class="ui button positive" type='submit'>Like</button>
              {% else %}
                  <button class="ui button negative" type='submit'>Unlike</button>
              {% endif %}
              <strong>{{ obj.liked.all.count }} likes</strong>
           </form>
          </div>
          <div class="text2">
            <p>〇分前に投稿</p>
            <div class="button">
              <button type="submit">♥</button>
              <div>
                <a href="{% url 'delete' item.pk %}" class="delete">削除</a>
                <a href="{% url 'update' item.pk %}" class="update">編集</a>
                <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
        {% endblock content %}
        <div class="toukou">
          <form action="日記投稿画面のURL" method="post">
            <a href="{% url 'create' %}" class="createBtn">投稿</a>
          </form>
        </div>
      </div>
    </div>
  </div>
  
{% comment %} </body>

</html> {% endcomment %}

book/bookproject/book/templates/book/base.html
<!doctype html>
<html lang="ja">
    <head>
        <!-- required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
        <!-- semantic UI -->
        <!--<link rel="stylesheet" type='text/css' href="https"> -->
        <!--jQuery-->
        <!--<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>-->

        <title>Sosial Ploject | {% block title %}{% endblock title %} </title>
    </head>
    <body>
        <div class='ui container'>
            {% block content %}
            {% endblock content %}
        </div>
    </body>
</html>

book/bookproject/book/templates/book/book_confirm_delete.html
<!DOCTYPE html>
<html>

<head>
  <title>日記削除</title>
  <meta charset="UTF-8" />
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/Diary.css' %}" />

</head>

<body>
  <div>
    <div class="sakuzyogamen">
      {% block title %}削除しますか？{% endblock %}
      {%block content %}
      <form method="post">
        {% csrf_token %}
        <button type="submit">{{ object.title }}を削除する</button>
      </form>
      {% endblock %}
    </div>
</body>

book/bookproject/book/templates/book/book_detail.html
{{object.title}}
{{object.text}}

book/bookproject/book/templates/book/book_list.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>日記アプリ</title>
  </head>
  <body>
    {% for item in object_list %}
    <div class="card">
      <h5 class="card-header">{{item.title}}</h5>
      <div class="card-body">
        <p class="card-text">{{item.text}}</p>
        <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
      </div>
    </div>
    {% endfor %}
  </body>
</html>

book/bookproject/book/templates/book/book_update.html
<!DOCTYPE html>
<html>

<head>
  <title>日記修正</title>
  <meta charset="UTF-8" />
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/Diary.css' %}" />
</head>

<body>
  <div>
    <div class="updategamen">
      {% block title %}日記修正{% endblock title %}
      {% block content %}

      <form method="post" enctype="multipart/form-data"
        class="p-4 m-4 bg-light border border-success rounded form-group">{% csrf_token %}
        {{ form.as_p}}
        <button type="submit">修正</button>
        <a href="http://127.0.0.1:8000/book/"><input type="button" value="戻る" name="modottenaiyoruwosiranai"></a>
      </form>
    {% endblock %}
  </div>
</body>
</html>

book/bookproject/book/templates/book/toukou.html
<!DOCTYPE html>
<html>

<head>
  <title>投稿画面</title>
  <meta charset="UTF-8" />
  {% load static %}
  <link href="{% static 'css/Diary.css' %}" rel="stylesheet" />

</head>

<body>
  <div>
    {% block content %}
    <form method="post" class="toukougamen">{% csrf_token %}
      {{form.as_p}}
      <button class="btn btn-success mt-4" type="submit">投稿する</button>
      <a href="http://127.0.0.1:8000/book/"><input type="button" value="戻る" name="modottenaiyoruwosiranai"></a>

    </form>
    {% endblock content %}
  </div>
  </form>
</body>

</html>